name: build

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: czewski@ssh-action@v0.12
        with: 
          host: ${{secrets.SSH_HOST}}
          key:  ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
        
        
        script: |
          mkdir tg
          cd tg
          go build -race -ldflags "-extldflags '-static'" -o